start_recording:
  fields:
    guid:
      required: false
      example: "245EBE933C0A597EBE865C0A245E0002"
      selector:
        text:
    entity_id:
      required: false
      example: "camera.qvr_surveillance_camera_1"
      selector:
        entity:
          domain: camera
    channel_index:
      required: false
      example: 1
      selector:
        number:
          min: 1
          max: 64
          mode: slider

stop_recording:
  fields:
    guid:
      required: false
      example: "245EBE933C0A597EBE865C0A245E0002"
      selector:
        text:
    entity_id:
      required: false
      example: "camera.qvr_surveillance_camera_1"
      selector:
        entity:
          domain: camera
    channel_index:
      required: false
      example: 1
      selector:
        number:
          min: 1
          max: 64
          mode: slider

reconnect:
  description: Force reconnection to QVR (re-authenticate).

ptz_control:
  fields:
    guid:
      required: false
      example: "245EBE933C0A597EBE865C0A245E0002"
      selector:
        text:
    entity_id:
      required: false
      example: "camera.qvr_surveillance_camera_1"
      selector:
        entity:
          domain: camera
    channel_index:
      required: false
      example: 1
      selector:
        number:
          min: 1
          max: 64
          mode: slider
    action_id:
      required: true
      selector:
        text:
    direction:
      selector:
        text:
