start_recording:
  fields:
    guid:
      required: true
      example: "245EBE933C0A597EBE865C0A245E0002"
      selector:
        text:

stop_recording:
  fields:
    guid:
      required: true
      example: "245EBE933C0A597EBE865C0A245E0002"
      selector:
        text:

reconnect:
  description: Force reconnection to QVR (re-authenticate).

ptz_control:
  fields:
    guid:
      required: true
      example: "245EBE933C0A597EBE865C0A245E0002"
      selector:
        text:
    action_id:
      required: true
      selector:
        text:
    direction:
      selector:
        text:
